on:
  push:
    tags:
      - '*.*.*'

name: Publish shy-sh to PyPI

jobs:
  build:
    name: Release to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.4
      - name: Install dependencies
        run: poetry config pypi-token.pypi ${{ secrets.PYPY_API_TOKEN }}
      - name: Set version
        run: poetry version ${{ github.ref }}
      - name: Publish package
        run: poetry publish --build
