on:
  - push

name: Tests

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.4
      - name: Install dependencies
        run: poetry install
      - name: Test
        run: poetry run pytest
